# 1.문제 정의

In [2]:
import numpy as np
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('/content/drive/MyDrive/2023-2알고리즘/[Project] 주어진 행렬 공간 중에서 최대 volume 구하기/input.csv')
vectors = data.iloc[0:20].to_numpy()  # 첫 행은 인덱스, 나머지가 벡터 값

# 초기 설정
num_vectors = 20    # 행렬의 행 수
population_size = 100  # 인구 크기
vector_length = 10000  # 전체 벡터의 수 설정 (예시로 10000으로 가정)
num_generations = 100  # 세대 수
mutation_rate = 0.1   # 돌연변이율
print(vectors.shape)

(20, 10000)


# 2. 초기 인구 생성


In [3]:
def initialize_population(pop_size, num_vectors):
    # 각 행렬의 열이 중복되지 않도록 선택
    population = []
    for _ in range(pop_size):
        x_indices = np.random.choice(num_vectors, 2, replace=False)
        if x_indices[0]>x_indices[1]:
          x_indices[0], x_indices[1] = x_indices[1], x_indices[0]
        y_indices = np.random.choice(vector_length, 2, replace=False)
        if y_indices[0]>y_indices[1]:
          y_indices[0], y_indices[1] = y_indices[1], y_indices[0]
        indices = np.stack((x_indices, y_indices), axis=-1)
        population.append(indices)
    return np.array(population)

# x와 y 좌표를 결합하여 2차원 인덱스 생성
population = initialize_population(population_size, num_vectors)
print(population)
population = population.reshape(100,4).tolist()

print(population)

[[[   2  134]
  [  12 1532]]

 [[   0 2656]
  [   3 3823]]

 [[   6 3075]
  [  17 8134]]

 [[   8 7520]
  [  17 9323]]

 [[  13  777]
  [  18 4074]]

 [[   2 4363]
  [  19 8619]]

 [[  15 6798]
  [  16 7488]]

 [[   6 2272]
  [   7 2520]]

 [[   1 7997]
  [  19 8080]]

 [[  12 8603]
  [  17 8847]]

 [[  16 6046]
  [  19 6494]]

 [[   5 4242]
  [  15 4714]]

 [[   3 1623]
  [   4 7178]]

 [[   2  670]
  [  16 7815]]

 [[  14 3393]
  [  15 4311]]

 [[   5 6930]
  [  19 8749]]

 [[   0 2481]
  [  10 9549]]

 [[   1 1608]
  [  15 9360]]

 [[   8  528]
  [  10 8385]]

 [[   1 6259]
  [   8 8635]]

 [[   6 4361]
  [  13 5000]]

 [[   2 3475]
  [  17 5838]]

 [[   6 2181]
  [  15 9104]]

 [[   4 2453]
  [  19 8409]]

 [[  12 1589]
  [  14 2778]]

 [[   1 2029]
  [   3 9712]]

 [[   1 7278]
  [   9 8725]]

 [[  18 1739]
  [  19 7729]]

 [[   1 2453]
  [   5 8483]]

 [[   6 3623]
  [  11 5889]]

 [[   7 6855]
  [   9 7989]]

 [[   5  643]
  [  19  676]]

 [[   6  245]
  [  14 1019]]

 [[   6  4

# 3. 적합도 함수 정의


In [4]:
def fitness(matrix):
    matrix_product = np.dot(matrix, matrix.transpose())
    matrix_det = np.linalg.det(matrix_product)
    if np.abs(matrix_det) < 1e-5:  # 행렬식이 매우 작은 경우 낮은 적합도 반환
        return 0
    volume = np.sqrt(np.abs(matrix_det))
    return volume

# print(fitness(vectors))

def evaluate_population(vectors):
    fitness_scores = []
    # population (100, 100, 20, 2) 100개의 개체군이 각각(100x20) 행렬로 이루어져 있으며,
    # 각 개체군의 요소는 vectors의 index [x, y]쌍으로 가지고 있다.
    for individual in population:
      print("individual: ", individual)

      # 각 개체군을 가져옴. mtx.shape = (100, 20, 20)
      # 각 개체의 인덱스를 사용하여 vectors에서 실제 값을 가져와 행렬을 생성
      matrix = np.array(vectors[individual[0]:individual[2], individual[1]:individual[3]])
      print(matrix.shape)

      # Volume 계산 결과와 indexing한 좌표를 저장함.
      fitness_scores.append([fitness(matrix), individual])
    return np.array(fitness_scores)



fitness_scores = evaluate_population(vectors)
print(len(fitness_scores))
print(fitness_scores.shape)
print(*fitness_scores, sep = '\n')

individual:  [2, 134, 12, 1532]
(10, 1398)
individual:  [0, 2656, 3, 3823]
(3, 1167)
individual:  [6, 3075, 17, 8134]
(11, 5059)
individual:  [8, 7520, 17, 9323]
(9, 1803)
individual:  [13, 777, 18, 4074]
(5, 3297)
individual:  [2, 4363, 19, 8619]
(17, 4256)
individual:  [15, 6798, 16, 7488]
(1, 690)
individual:  [6, 2272, 7, 2520]
(1, 248)
individual:  [1, 7997, 19, 8080]
(18, 83)
individual:  [12, 8603, 17, 8847]
(5, 244)
individual:  [16, 6046, 19, 6494]
(3, 448)
individual:  [5, 4242, 15, 4714]
(10, 472)
individual:  [3, 1623, 4, 7178]
(1, 5555)
individual:  [2, 670, 16, 7815]
(14, 7145)
individual:  [14, 3393, 15, 4311]
(1, 918)
individual:  [5, 6930, 19, 8749]
(14, 1819)
individual:  [0, 2481, 10, 9549]
(10, 7068)
individual:  [1, 1608, 15, 9360]
(14, 7752)
individual:  [8, 528, 10, 8385]
(2, 7857)
individual:  [1, 6259, 8, 8635]
(7, 2376)
individual:  [6, 4361, 13, 5000]
(7, 639)
individual:  [2, 3475, 17, 5838]
(15, 2363)
individual:  [6, 2181, 15, 9104]
(9, 6923)
individual:  

<ipython-input-4-24aef6b52d69>:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(fitness_scores)


# 4. 선택

In [5]:
# 4. 선택
def select_parents(fitness_scores):
    # 적합도 점수만 추출
    scores = [score[0] for score in fitness_scores]

    # 총 적합도 점수 계산
    total_fitness = sum(scores)

    # 각 개체의 선택 확률 계산
    probabilities = [score / total_fitness for score in scores]

    # 선택 확률에 따라 부모를 무작위로 선택
    selected_indices = np.random.choice(len(fitness_scores), size=len(fitness_scores), replace=True, p=probabilities)

    # 선택된 인덱스를 기반으로 부모 선택
    parents = [fitness_scores[index] for index in selected_indices]
    return np.array(parents)

# 적합도 점수를 바탕으로 부모 선택
parents = select_parents(fitness_scores)

# 선택된 부모 출력
print(parents.shape)
print(parents)

(100, 2)
[[6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+30 list([2, 4363, 19, 8619])]
 [6.612527557715143e+3

# 5. 교차

In [6]:
# 5. 교차
def crossover(parents):
    offspring = []
    num_parents = len(parents)

    for i in range(0, num_parents - 1, 2):
        # 부모 개체 선택
        parent1 = parents[i][1]
        parent2 = parents[i + 1][1]

        # 교차 위치 선택 (부모 배열의 길이에 따라 조정)
        cut = np.random.randint(1, len(parent1) - 1)

        # 자손 생성
        child1 = np.concatenate([parent1[:cut], parent2[cut:]])
        child2 = np.concatenate([parent2[:cut], parent1[cut:]])

        offspring.extend([child1, child2])

    # 부모 배열의 길이가 홀수인 경우 마지막 부모 처리
    if num_parents % 2 != 0:
        offspring.append(parents[-1][1])

    return np.array(offspring)

# 교차 함수 호출 및 자손 출력
offspring = crossover(parents)
print(offspring)

[[   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   1 4363   19 8619]
 [   2 1193   17 6463]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363   19 8619]
 [   2 4363

# 6. 돌연변이

In [7]:
# 6. 돌연변이
def mutation(offspring_crossover, mutation_rate, num_vectors, vector_length):
    for idx in range(offspring_crossover.shape[0]):
        if np.random.rand() < mutation_rate:
            # 돌연변이가 발생할 유전자 위치 선택
            gene_idx = np.random.randint(4)  # 0에서 3 사이의 정수 (x1, y1, x2, y2 중 하나)

            # 돌연변이 적용
            if gene_idx % 2 == 0:  # x1 또는 x2의 경우
                random_value = np.random.randint(num_vectors)
            else:  # y1 또는 y2의 경우
                random_value = np.random.randint(vector_length)

            # 돌연변이 적용
            offspring_crossover[idx, gene_idx] = random_value
    return offspring_crossover

# 돌연변이 함수 호출
mutated_offspring = mutation(offspring, mutation_rate, num_vectors, vector_length)


# 7-8. 새로운 세대 생성 및 종료 조건 검사

In [10]:
best_fitness = 0
fitness_threshold = 796727301049202.6  # 최대 적합도 종료 임계값

for generation in range(num_generations):
    # 적합도 평가
    fitness_scores = evaluate_population(vectors)
    # 이번 세대의 최대 적합도
    max_fitness_this_generation = max(score[0] for score in fitness_scores)

    # 최대 적합도가 이전 최고값을 초과하는 경우 업데이트
    if max_fitness_this_generation > best_fitness:
        best_fitness = max_fitness_this_generation

    # 종료 조건 검사: 최대 적합도가 임계값 이상인 경우
    if best_fitness >= fitness_threshold:
        print(f"Generation {generation}: 최대 적합도가 {fitness_threshold} 이상이므로 종료합니다.")
        break

    # 부모 선택
    parents = select_parents(fitness_scores)  # 여기서 population 인자 제거

    # 교차
    offspring = crossover(parents)  # 여기서 두 번째 인자 제거

    # 돌연변이 적용
    mutated_offspring = mutation(offspring, mutation_rate, num_vectors, vector_length)

    # 새로운 개체군 생성
    population = mutated_offspring

    print(f"Generation {generation}: 최대 적합도 = {best_fitness}")


individual:  [2, 134, 12, 1532]
(10, 1398)
individual:  [0, 2656, 3, 3823]
(3, 1167)
individual:  [6, 3075, 17, 8134]
(11, 5059)
individual:  [8, 7520, 17, 9323]
(9, 1803)
individual:  [13, 777, 18, 4074]
(5, 3297)
individual:  [2, 4363, 19, 8619]
(17, 4256)
individual:  [15, 6798, 16, 7488]
(1, 690)
individual:  [6, 2272, 7, 2520]
(1, 248)
individual:  [1, 7997, 19, 8080]
(18, 83)
individual:  [12, 8603, 17, 8847]
(5, 244)
individual:  [16, 6046, 19, 6494]
(3, 448)
individual:  [5, 4242, 15, 4714]
(10, 472)
individual:  [3, 1623, 4, 7178]
(1, 5555)
individual:  [2, 670, 16, 7815]
(14, 7145)
individual:  [14, 3393, 15, 4311]
(1, 918)
individual:  [5, 6930, 19, 8749]
(14, 1819)
individual:  [0, 2481, 10, 9549]
(10, 7068)
individual:  [1, 1608, 15, 9360]
(14, 7752)
individual:  [8, 528, 10, 8385]
(2, 7857)
individual:  [1, 6259, 8, 8635]
(7, 2376)
individual:  [6, 4361, 13, 5000]
(7, 639)
individual:  [2, 3475, 17, 5838]
(15, 2363)
individual:  [6, 2181, 15, 9104]
(9, 6923)
individual:  

<ipython-input-4-24aef6b52d69>:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(fitness_scores)


# 9. 결과 추출

In [11]:
final_fitness = evaluate_population(population, vectors)
best_index = np.argmax(final_fitness)
best_solution = population[best_index]
best_volume = final_fitness[best_index]

print("최대 볼륨:", best_volume)
print("해당 벡터의 인덱스:", best_solution)


TypeError: ignored