# 1.문제 정의

In [87]:
import numpy as np
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('/content/drive/MyDrive/2023-2알고리즘/[Project] 주어진 행렬 공간 중에서 최대 volume 구하기/input.csv')
vectors = data.iloc[1:21].to_numpy()  # 첫 행은 인덱스, 나머지가 벡터 값

# 초기 설정
num_vectors = 20    # 행렬의 행 수
population_size = 100  # 인구 크기
vector_length = 10000  # 전체 벡터의 수 설정 (예시로 10000으로 가정)
num_generations = 100  # 세대 수
mutation_rate = 0.1   # 돌연변이율
print(vectors)

[[ 0.09130457  0.31296659 -0.3277619  ...  0.17386052 -0.49610621
   0.95447834]
 [-1.94118936  0.63436125  0.21332334 ...  2.63566329  0.98461692
  -2.05137763]
 [ 1.20599072  0.63773173  0.37202377 ...  0.1490941  -0.16698097
   0.70955588]
 ...
 [-1.51843521  0.6081658   0.01824384 ...  2.1008383  -0.13667624
  -0.88527608]
 [ 1.31471571 -1.06830117 -0.25633056 ... -1.24862182  0.09704474
   1.50861745]
 [ 1.23136462 -0.02520689  0.74379476 ...  0.345985   -2.36028857
   1.78184592]]


# 2. 초기 인구 생성


In [100]:
def initialize_population(pop_size, num_vectors):
    # x 좌표를 0부터 19 사이에서 선택
    x_indices = np.random.randint(0, num_vectors-1, size=(pop_size, num_vectors)) # num_vectors-1 대신 num_vectors 사용

    # y 좌표를 0부터 9999 사이에서 선택
    y_indices = np.random.randint(0, vector_length-1, size=(pop_size, num_vectors))

    # x와 y 좌표를 결합하여 2차원 인덱스 생성
    indices = np.stack((x_indices, y_indices), axis=-1)

    return indices

# x와 y 좌표를 결합하여 2차원 인덱스 생성
population = initialize_population(population_size, num_vectors)

for _ in range(99):
    population = np.concatenate((population, initialize_population(population_size, num_vectors)), axis=0)
population = population.reshape(100,100,20,2)
print("population size: ", population.shape)
print(population)

population size:  (100, 100, 20, 2)
[[[[  10 6820]
   [  14 4327]
   [  16   52]
   ...
   [  10 3509]
   [  16 1181]
   [   7 3329]]

  [[   9 2005]
   [   5 9576]
   [  11 9762]
   ...
   [  13 9224]
   [  11 5544]
   [  16 4548]]

  [[  14 4045]
   [   1 2255]
   [  12 3292]
   ...
   [   5 2817]
   [  12 9575]
   [   7 2261]]

  ...

  [[   6 8012]
   [  15 1896]
   [  13 2945]
   ...
   [   3 3113]
   [   9 4028]
   [   9 4807]]

  [[  13 1127]
   [   4 8544]
   [  14 3325]
   ...
   [  12 2089]
   [  18 2616]
   [  14 7290]]

  [[   4 6225]
   [   1 7384]
   [   4 4771]
   ...
   [  16 7870]
   [  17 4291]
   [  18 4381]]]


 [[[  13    7]
   [   3  581]
   [   2 3700]
   ...
   [   8  200]
   [  18 6383]
   [  11 1683]]

  [[  13 1504]
   [  11 8818]
   [   7 9608]
   ...
   [  14 7631]
   [   3 4516]
   [  14 4213]]

  [[   5 4119]
   [  11  912]
   [   5 9771]
   ...
   [   2 7376]
   [   9 6504]
   [  10 1692]]

  ...

  [[  18 1682]
   [   7 7567]
   [  10 2083]
   ...
   [ 

# 3. 적합도 함수 정의


In [102]:
# 3. 적합도 함수 정의
def fitness(matrix):
    matrix_product = np.dot(matrix, matrix.transpose())
    print('matrix_product: ', matrix_product)
    print('matrix_det: ', np.linalg.det(matrix_product))
    volume = np.sqrt(np.abs(np.linalg.det(matrix_product))) # sqrt(|det(A^T * A)|)
    print("volume: ", volume)
    return volume

def evaluate_population(vectors):
    fitness_scores = []
    # population (100, 100, 20, 2) 100개의 개체군이 각각(100x20) 행렬로 이루어져 있으며,
    # 각 개체군의 요소는 vectors의 index [x, y]쌍으로 가지고 있다.
    for mtx in population:
      # 각 개체군을 가져옴. mtx.shape = (100, 20, 20)
      matrix = []
      for individual in mtx:
        # 각 개체의 인덱스를 사용하여 vectors에서 실제 값을 가져와 행렬을 생성
        matrix.append([vectors[x, y] for x, y in individual])
      matrix = np.array(matrix)
      print("matrix")
      print(matrix)
      print(fitness(matrix))
      fitness_scores.append(fitness(matrix))
    return np.array(fitness_scores)



fitness_scores = evaluate_population(vectors)
print(fitness_scores.shape)
print(*fitness_scores, sep = '\n')

matrix
[[-1.2953304   0.13118417 -0.42426771 ...  0.45009548  1.19219851
  -0.43796637]
 [ 0.97015128  0.84075962 -0.23972384 ... -1.18650701  0.69578712
  -2.43824892]
 [-0.01341193  1.90736918  1.09335036 ...  0.18479405  2.04009165
  -2.16189451]
 ...
 [ 0.42935927  1.04094403 -0.15783788 ...  0.31854991  2.34227825
  -1.08383353]
 [-1.00177957  0.76711552  0.8688278  ... -0.46772964  0.62443729
   0.22150753]
 [-0.34445102 -0.88259509 -0.38154204 ... -0.08335899  0.63163851
   0.0039683 ]]
matrix_product:  [[15.96732388  4.4846324   1.73756287 ... 11.03758132  1.22706748
   1.35749735]
 [ 4.4846324  17.61194762  5.05502764 ...  9.79793965  4.84764586
   0.14300959]
 [ 1.73756287  5.05502764 25.50522603 ...  8.96614162  3.06995607
  -2.45182243]
 ...
 [11.03758132  9.79793965  8.96614162 ... 31.97217399 14.80539328
   4.28260482]
 [ 1.22706748  4.84764586  3.06995607 ... 14.80539328 18.89642353
   1.72876961]
 [ 1.35749735  0.14300959 -2.45182243 ...  4.28260482  1.72876961
   8.194

# 4. 선택

In [77]:
def select_parents(population, fitness_scores):
    # fitness_scores.sum()이 0인 경우 예외 처리
    if fitness_scores.sum() == 0:
        # 확률을 균등하게 설정
        probabilities = np.ones(len(fitness_scores)) / len(fitness_scores)
    else:
        probabilities = fitness_scores / fitness_scores.sum()

    selected_indices = np.random.choice(len(population), size=len(population), replace=True, p=probabilities)
    return population[selected_indices]

parents = select_parents(population, fitness_scores)

# 5. 교차

In [78]:
def crossover(parents):
    offspring = []
    for i in range(0, len(parents), 2):
        parent1 = parents[i]
        parent2 = parents[i + 1]
        cut = np.random.randint(1, len(parent1)-1)
        child1 = np.concatenate([parent1[:cut], parent2[cut:]])
        child2 = np.concatenate([parent2[:cut], parent1[cut:]])
        offspring.extend([child1, child2])
    return np.array(offspring)

offspring = crossover(parents)


# 6. 돌연변이

In [79]:
# 돌연변이 함수
def mutation(offspring_crossover, mutation_rate, num_vectors):
    for idx in range(offspring_crossover.shape[0]):
        if np.random.rand() < mutation_rate:
            random_index = np.random.randint(offspring_crossover.shape[1])
            random_value = np.random.randint(num_vectors)
            offspring_crossover[idx, random_index] = random_value
    return offspring_crossover
# 돌연변이 함수 호출
num_vectors = 10000  # 전체 벡터의 수 설정
mutated_offspring = mutation(offspring, mutation_rate, num_vectors)


# 7-8. 새로운 세대 생성 및 종료 조건 검사

In [80]:
for generation in range(num_generations):
    fitness_scores = evaluate_population(population, vectors)
    parents = select_parents(population, fitness_scores)
    offspring = crossover(parents)  # 여기서 두 번째 인자 제거
    mutated_offspring = mutation(offspring, mutation_rate, num_vectors)
    population = mutated_offspring
    # 종료 조건 검사
    # ...


TypeError: ignored

# 9. 결과 추출

In [81]:
final_fitness = evaluate_population(population, vectors)
best_index = np.argmax(final_fitness)
best_solution = population[best_index]
best_volume = final_fitness[best_index]

print("최대 볼륨:", best_volume)
print("해당 벡터의 인덱스:", best_solution)


TypeError: ignored