# 1.문제 정의

In [5]:
import numpy as np
import pandas as pd

# 데이터 불러오기
data = pd.read_csv('/content/drive/MyDrive/2023-2알고리즘/[Project] 주어진 행렬 공간 중에서 최대 volume 구하기/input.csv')
vectors = data.iloc[0:20].to_numpy()  # 첫 행은 인덱스, 나머지가 벡터 값

# 초기 설정
num_vectors = 20    # 행렬의 행 수
population_size = 100  # 인구 크기
vector_length = 10000  # 전체 벡터의 수 설정 (예시로 10000으로 가정)
num_generations = 100  # 세대 수
mutation_rate = 0.1   # 돌연변이율
print(vectors.shape)

(20, 10000)


# 2. 초기 인구 생성


In [33]:
def initialize_population(pop_size, num_vectors):
    # 각 행렬의 열이 중복되지 않도록 선택
    population = []
    for _ in range(pop_size):
        x_indices = np.random.choice(num_vectors, 2, replace=False)
        if x_indices[0]>x_indices[1]:
          x_indices[0], x_indices[1] = x_indices[1], x_indices[0]
        y_indices = np.random.choice(vector_length, 2, replace=False)
        if y_indices[0]>y_indices[1]:
          y_indices[0], y_indices[1] = y_indices[1], y_indices[0]
        indices = np.stack((x_indices, y_indices), axis=-1)
        population.append(indices)
    return np.array(population)

# x와 y 좌표를 결합하여 2차원 인덱스 생성
population = initialize_population(population_size, num_vectors)
print(population)
population = population.reshape(100,4).tolist()

print(population)

[[[   0 2047]
  [  19 5652]]

 [[  10 1750]
  [  18 8620]]

 [[   9  918]
  [  17 1748]]

 [[   1  250]
  [   7 6673]]

 [[   3 6711]
  [   8 7985]]

 [[   9  169]
  [  16 1274]]

 [[   3 2620]
  [  19 5834]]

 [[  16 5732]
  [  19 9290]]

 [[  11 2490]
  [  12 4228]]

 [[   9 3716]
  [  14 9963]]

 [[   3  690]
  [   6 6209]]

 [[   0 2147]
  [   9 5526]]

 [[   0  250]
  [  19 3883]]

 [[   6 2324]
  [   9 7260]]

 [[   6 3556]
  [   7 9832]]

 [[   4 1867]
  [  14 6144]]

 [[   0 3000]
  [  18 3114]]

 [[   3   16]
  [   8 9910]]

 [[  16 1718]
  [  19 6647]]

 [[   4 3374]
  [  10 8817]]

 [[   0 3702]
  [   9 6466]]

 [[   2 3845]
  [   4 3980]]

 [[  10 1107]
  [  15 2888]]

 [[   8 1089]
  [  11 9297]]

 [[   5  750]
  [   6 6554]]

 [[   1 1014]
  [   9 1542]]

 [[  11 2943]
  [  17 7938]]

 [[  11 3246]
  [  19 4081]]

 [[   7 1021]
  [  16 1652]]

 [[   4 6337]
  [   5 6662]]

 [[  11 6163]
  [  18 8597]]

 [[   9 6544]
  [  13 8989]]

 [[  10 4487]
  [  17 9695]]

 [[   1  4

# 3. 적합도 함수 정의


In [63]:
# 3. 적합도 함수 정의
def fitness(matrix):
    matrix_product = np.dot(matrix, matrix.transpose())
    matrix_det = np.linalg.det(matrix_product)
    if np.abs(matrix_det) < 1e-5:  # 행렬식이 매우 작은 경우 낮은 적합도 반환
        return 0
    volume = np.sqrt(np.abs(matrix_det))
    return volume

# print(fitness(vectors))

def evaluate_population(vectors):
    fitness_scores = []
    # population (100, 100, 20, 2) 100개의 개체군이 각각(100x20) 행렬로 이루어져 있으며,
    # 각 개체군의 요소는 vectors의 index [x, y]쌍으로 가지고 있다.
    for individual in population:
      print("individual: ", individual)

      # 각 개체군을 가져옴. mtx.shape = (100, 20, 20)
      # 각 개체의 인덱스를 사용하여 vectors에서 실제 값을 가져와 행렬을 생성
      matrix = np.array(vectors[individual[0]:individual[2], individual[1]:individual[3]])
      print(matrix.shape)
      # print(matrix.shape)
      # print("matrix")
      # print(matrix)
      # print(fitness(matrix))
      # Volume 계산 결과와 indexing한 좌표를 저장함.
      fitness_scores.append([fitness(matrix), individual])
    return np.array(fitness_scores)



fitness_scores = evaluate_population(vectors)
print(fitness_scores.shape)
print(*fitness_scores, sep = '\n')

individual:  [0, 2047, 19, 5652]
(19, 3605)
individual:  [10, 1750, 18, 8620]
(8, 6870)
individual:  [9, 918, 17, 1748]
(8, 830)
individual:  [1, 250, 7, 6673]
(6, 6423)
individual:  [3, 6711, 8, 7985]
(5, 1274)
individual:  [9, 169, 16, 1274]
(7, 1105)
individual:  [3, 2620, 19, 5834]
(16, 3214)
individual:  [16, 5732, 19, 9290]
(3, 3558)
individual:  [11, 2490, 12, 4228]
(1, 1738)
individual:  [9, 3716, 14, 9963]
(5, 6247)
individual:  [3, 690, 6, 6209]
(3, 5519)
individual:  [0, 2147, 9, 5526]
(9, 3379)
individual:  [0, 250, 19, 3883]
(19, 3633)
individual:  [6, 2324, 9, 7260]
(3, 4936)
individual:  [6, 3556, 7, 9832]
(1, 6276)
individual:  [4, 1867, 14, 6144]
(10, 4277)
individual:  [0, 3000, 18, 3114]
(18, 114)
individual:  [3, 16, 8, 9910]
(5, 9894)
individual:  [16, 1718, 19, 6647]
(3, 4929)
individual:  [4, 3374, 10, 8817]
(6, 5443)
individual:  [0, 3702, 9, 6466]
(9, 2764)
individual:  [2, 3845, 4, 3980]
(2, 135)
individual:  [10, 1107, 15, 2888]
(5, 1781)
individual:  [8, 108

<ipython-input-63-e1a147b4a6bb>:28: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.array(fitness_scores)


# 4. 선택

In [55]:
def select_parents(population, fitness_scores):
    # fitness_scores.sum()이 0인 경우 예외 처리
    if fitness_s cores.sum() == 0:
        # 확률을 균등하게 설정
        probabilities = np.ones(len(fitness_scores)) / len(fitness_scores)
    else:
        probabilities = fitness_scores / fitness_scores.sum()

    selected_indices = np.random.choice(len(population), size=len(population), replace=True, p=probabilities)
    return population[selected_indices]

parents = select_parents(population, fitness_scores)

TypeError: ignored

# 5. 교차

In [ ]:
def crossover(parents):
    offspring = []
    for i in range(0, len(parents), 2):
        parent1 = parents[i]
        parent2 = parents[i + 1]
        cut = np.random.randint(1, len(parent1)-1)
        child1 = np.concatenate([parent1[:cut], parent2[cut:]])
        child2 = np.concatenate([parent2[:cut], parent1[cut:]])
        offspring.extend([child1, child2])
    return np.array(offspring)

offspring = crossover(parents)


# 6. 돌연변이

In [ ]:
# 돌연변이 함수
def mutation(offspring_crossover, mutation_rate, num_vectors):
    for idx in range(offspring_crossover.shape[0]):
        if np.random.rand() < mutation_rate:
            random_index = np.random.randint(offspring_crossover.shape[1])
            random_value = np.random.randint(num_vectors)
            offspring_crossover[idx, random_index] = random_value
    return offspring_crossover
# 돌연변이 함수 호출
num_vectors = 10000  # 전체 벡터의 수 설정
mutated_offspring = mutation(offspring, mutation_rate, num_vectors)


# 7-8. 새로운 세대 생성 및 종료 조건 검사

In [ ]:
for generation in range(num_generations):
    fitness_scores = evaluate_population(population, vectors)
    parents = select_parents(population, fitness_scores)
    offspring = crossover(parents)  # 여기서 두 번째 인자 제거
    mutated_offspring = mutation(offspring, mutation_rate, num_vectors)
    population = mutated_offspring
    # 종료 조건 검사
    # ...


TypeError: ignored

# 9. 결과 추출

In [ ]:
final_fitness = evaluate_population(population, vectors)
best_index = np.argmax(final_fitness)
best_solution = population[best_index]
best_volume = final_fitness[best_index]

print("최대 볼륨:", best_volume)
print("해당 벡터의 인덱스:", best_solution)


TypeError: ignored